"""
Cache Key
"""
MUTATION_LOCK_PREFIX = 'l_mut'
PREPAID_PRODUCT_BY_CODE = "prod_{}"
AGENT_BY_AGENTID = "agent_{}"
AGENTID_BY_REQPROTOCOL = "prot_{}"
AGENT_BY_MSISDN = "agent_msisdn_{}"
VENDOR_PTYPE = "vendor_ptype_{}"
CK_OTP_USER = "OTP:{}"
CK_REG_USER = "REG:{}"
CK_KTP_IMG = "ktp_{}"
CK_PIN_TRX = "PIN:{}"
CK_SELFIE_IMG = "selfie_{}"
CK_OUTLET_IMG = "outlet_{}"
CK_HISTORY_TRANSACTION = "HISTORY:TRANSACTION:DETAIL:{}"
CK_HISTORY_TRANSACTION_PREPAID = "HISTORY:TRANSACTIONPREPAID:DETAIL:{}"
CK_HISTORY_TRANSACTION_MULTIBILLER = "HISTORY:TRANSACTIONMULTIBILLER:DETAIL:{}"
CK_HISTORY_TRANSACTION_TRANSFER = "HISTORY:TRANSACTIONTRANSFER:DETAIL:{}"
CK_QUERY_BY_OPERATORID = "query_{}"
CK_QUERY_CPP_BY_OPERATORID = "query_cpp_{}{}"
CK_PREPAID_BY_OPERATORID = "prepaid_list_{}"
CK_CUSTOM_PREPAID_BY_OPERATORID = "prepaid_list_custom_{}{}"
CK_PREPAID_QUEUE = "preapid_queue_{}{}{}{}"
CK_POSTPAID_QUEUE = "postpaid_queue_{}{}{}{}"
CK_AGENT_ACTIVE = "agent_active_{}"
CK_PRICE = "price_{}_{}"

"""
TTL
"""
TTLDAY = 86400
TTLSHORT = 1200
TTLINQ = 300
TTLHR = 3600